### ISSUE TITLE
抽象 hippo4j 核心组件，不依赖 server 端即可完成动态调参、监控、报警等功能

### ISSUE THREAD

**Issue by weihubeats** [acmenlt/dynamic-threadpool#103]
目前感觉不足的还是太过于重量导致会缺失部分用户。因为他们可能仅仅需要的是一个简单的sdk去支持报警和动态配置，无需服务器部署

**Comment by acmenlt** [comment]
抽象 hippo4j-core-spring-boot-starter 组件，不依赖 server 端完成动态调参、监控、报警等功能

**Comment by rezbp** [comment]
对，这个轻量级的功能大概什么时候可以更新呢

**Comment by acmenlt** [comment]
> 对，这个轻量级的功能大概什么时候可以更新呢

大概这这个周末会完成。因为功能抽象的内容不少，会费点时间
