### ISSUE TITLE
服务端事件机制

### ISSUE THREAD

**Issue by 872699467** [acmenlt/dynamic-threadpool#111]
大佬，服务端的```cn.hippo4j.config.event.AbstractEvent```事件为什么不继承ApplicationEvent，使用spring的消息机制。而是在```cn.hippo4j.config.notify.DefaultPublisher```使用一个消息队列BlockingQueue<AbstractEvent> queue，让线程在```cn.hippo4j.config.notify.DefaultPublisher#openEventHandler```方法中不断拉取队列中的消息，提醒订阅者。

**Comment by acmenlt** [comment]
hippo4j 最早参数动态是参考 nacos 来做的，延续了其设计。所以，你说的方案应该也可以实现，可以理解为不同的实现方法而已；而为什么 nacos 这么做，我理解它的业务场景肯定要比 hippo4j 更复杂

**Comment by 872699467** [comment]
> 

非常感谢您的建议，您说的问题自己也有切身体会。由于自己刚工作，在看代码时经常不断debug跟踪方法而陷入到方法的实现细节中，导致不能宏观掌握整体的流程。现在看您的代码也是从最先的0.1.0版本看起😂，要完全看懂每个方法的实现确实有些费时费力，还是要先掌握框架整体流程再读代码才会比较流畅吧，再次感谢您的指导。
