### ISSUE TITLE
为什么这个会跨域呢

### ISSUE THREAD

**Issue by jinhua-2** [acmenlt/dynamic-threadpool#125]
![image](https://user-images.githubusercontent.com/73089768/156520045-b6f39c72-9e19-44cb-bbd0-a09baa899451.png)

**Comment by acmenlt** [comment]
请确保 hippo4j 服务端部署在内网环境，并且与 hippo4j 客户端在同一网络下

**Comment by jinhua-2** [comment]
我的客户端项目是本机ip:8080   ,hippo4j 服务端是本机ip:6691。

**Comment by acmenlt** [comment]
我本地无法复现，请检查您本地的网络
是否有开外网，启动 server 与启动 client 时网络是否一致...

**Comment by jinhua-2** [comment]
你们提供的演示地址，也有这个问题    http://console.hippox.cn:6691/index.html#/hippo4j/threadPool/instanceList

**Comment by acmenlt** [comment]
这个问题很好，因为示例项目中，服务端部署在外网，而客户端IP是内网的，所以不通
