### ISSUE TITLE
关于配置中心只能二选一

### ISSUE THREAD

**Issue by LINGLUOJUN** [acmenlt/dynamic-threadpool#126]
目前我司内部 使用的内部自研的配置中心,starter好像没法直接支持上

**Comment by acmenlt** [comment]
提供配置中心 SPI 实现，计划在 1.1.1 版本支持

**Comment by acmenlt** [comment]
想了一下，如果自研的配置中心，你们自定义监听 Bean，发生变更后调用 AbstractCoreThreadPoolDynamicRefresh#dynamicRefresh 就好了

**Comment by acmenlt** [comment]
无响应，将关闭 Issue。
