### ISSUE TITLE
对已有线程池的无缝增强监控

### ISSUE THREAD

**Issue by weihubeats** [acmenlt/dynamic-threadpool#127]

**Comment by acmenlt** [comment]
这个怎么说

**Comment by weihubeats** [comment]
是否有考虑这样的场景，比如我想引入依赖对目前项目的所有线程池做一个监控，但没有侵入

**Comment by acmenlt** [comment]
基于这个想法我有两个问题

1. 我理解想要无侵入监控，至少线程池需要是个 Spring Bean 对么？或者你有什么想法实现
2. 想要的监控效果是什么样的，对接普罗米修斯，还是 Hippo4J Server

**Comment by weihubeats** [comment]
通过Agent + 字节码方式是可以实现的，监控效果最好是提供Endpoint端点，供用户自己扩展

**Comment by acmenlt** [comment]
我不认为一个轻量级的线程池监控，需要加一个 Agent；站在用户的角度上，希望越简单接入越好

相对于 Endpoint，更倾向 Metric 指标，上报监控
