### ISSUE TITLE
使用undertow时【server端-容器线程池-查看】负载情况显示null%

### ISSUE THREAD

**Issue by xqxyxchy** [acmenlt/dynamic-threadpool#148]
hippo4j版本：1.1.0
spring-boot版本：2.3.12.RELEASE
undertow版本：2.1.7.Final
server端-容器线程池-查看，负载情况显示null%
![hippo4j查看容器线程池-负载情况](https://user-images.githubusercontent.com/21134578/159100965-c27c2b45-d3d3-46c3-8dbe-c2caba1504ec.jpg)

**Comment by acmenlt** [comment]
1.1.0 版本对于 undertow 和 jetty 的详情查看功能支持不太好，您有兴趣提交 pr 么

**Comment by acmenlt** [comment]
已解决
