### ISSUE TITLE
apollo动态配置不生效

### ISSUE THREAD

**Issue by richardcode991** [acmenlt/dynamic-threadpool#162]
使用版本1.2.0
<img width="704" alt="image" src="https://user-images.githubusercontent.com/7203336/160550687-5e3d9504-a211-4a5e-9115-552c67a2d755.png">

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/7203336/160550571-466f4f4d-25f2-442b-a63d-9153c3ca5268.png">

getConfig和getConfigFile入参应该和上图一致。

getConfigFile 应该不带后缀吧。

配置：
   apollo:
        namespace: thread-pool.yml
      config-file-type: yml  # 配置中心文件格式

**Comment by acmenlt** [comment]
请参考 Apollo [动态配置示例模块](https://github.com/acmenlt/dynamic-threadpool/tree/develop/hippo4j-example/hippo4j-core-apollo-spring-boot-starter-example)，我测试是没问题的。

**Comment by richardcode991** [comment]
就是按照事例配置的，但是apollo非properties，namespaces需要加上后缀，如thread-pool.yml，这样ApolloRefresherHandler中Config config = ConfigService.getConfig(namespace)才会有内容；但是这样配置又导致configChangeListener中ConfigService.getConfigFile最后拼接的路径为thread-pool.yml.yml导致监听apollo变动获取不到内容。
------
我改成properties方式就正常了

**Comment by acmenlt** [comment]
> ## 你好
> ## 就是按照事例配置的，但是apollo非properties，namespaces需要加上后缀，如thread-pool.yml，这样ApolloRefresherHandler中Config config = ConfigService.getConfig(namespace)才会有内容；但是这样配置又导致configChangeListener中ConfigService.getConfigFile最后拼接的路径为thread-pool.yml.yml导致监听apollo变动获取不到内容。
> 我改成properties方式就正常了

@richardcode991 

apollo:
namespace: thread-pool
config-file-type: yml

改成这样试试呢

**Comment by richardcode991** [comment]
这样不行，这样ApolloRefresherHandler中Config config = ConfigService.getConfig(namespace)获取不到配置，导致监听注册不上去。

**Comment by acmenlt** [comment]
> 这样不行，这样ApolloRefresherHandler中Config config = ConfigService.getConfig(namespace)获取不到配置，导致监听注册不上去。

稍后我试下

**Comment by acmenlt** [comment]
@richardcode991 我对 apollo 不太熟悉，场景复现不出来。你有兴趣针对上述问题对 ApolloRefresherHandler 提个 PR 么

**Comment by richardcode991** [comment]
好的 后面我处理下

**Comment by acmenlt** [comment]
今天会为 Core 发布一个新的 RC 版本。

```xml
<dependency>
    <groupId>cn.hippo4j</groupId>
    <artifactId>hippo4j-core-spring-boot-starter</artifactId>
    <version>1.2.0-RC1</version>
</dependency>
```
