### ISSUE TITLE
建议不通过CommandLineRunner实现，而是监听Spring事件来实现

### ISSUE THREAD

**Issue by Gahon1995** [acmenlt/dynamic-threadpool#167]
1. 由于使用CommandLineRunner会导致其他bean如果先于执行，从而导致启动时无法发送通知

https://github.com/acmenlt/dynamic-threadpool/blob/8d90d14d5565639c7620cb1b130b8f4d7ddad216/hippo4j-common/src/main/java/cn/hippo4j/common/notify/HippoBaseSendMessageService.java#L25

2. 另外[这个地方](https://github.com/acmenlt/dynamic-threadpool/blob/8d90d14d5565639c7620cb1b130b8f4d7ddad216/hippo4j-spring-boot/hippo4j-core-spring-boot-starter/src/main/java/cn/hippo4j/core/starter/refresher/AbstractCoreThreadPoolDynamicRefresh.java#L83)，如果远程没有配置单独的告警的话，是不是应该加载默认的，和从配置文件中加载时的逻辑不一样

3. 不支持配置中心动态修改告警联系人这些配置么

**Comment by acmenlt** [comment]
@Gahon1995 
1. 第一个问题，线程池在项目启动时不应该发送报警通知，如果需要发送，应该考虑的是线程池配置是否合理。
2. 第二个问题没看明白。hippo4j 会默认加载远端的告警配置。
3. 目前不支持动态修改告警联系人，1.2.1 会支持。或者你可以提个 pr

**Comment by Gahon1995** [comment]
> @Gahon1995
> 
> 1. 第一个问题，线程池在项目启动时不应该发送报警通知，如果需要发送，应该考虑的是线程池配置是否合理。
> 2. 第二个问题没看明白。hippo4j 会默认加载远端的告警配置。
> 3. 目前不支持动态修改告警联系人，1.2.1 会支持。或者你可以提个 pr

1. 第一个问题主要在于如果本地的线程池配置和远端的不一致，这样的话在第一次加载远端配置时就会发生一次变更通知，而这个通知就又可能通知不到
2. 就是代码那个地方，如果远端没有为线程池配置单独告警的话，调用对应的`getNotify()`方法就会抛出异常

**Comment by acmenlt** [comment]
@Gahon1995 hippo4j-server 还是 hippo4j-core

**Comment by Gahon1995** [comment]
hippo4j-core的

**Comment by acmenlt** [comment]
@Gahon1995 

1. hippo4j-core 创建线程池是从远端拉配置的，不存在本地线程池配置与配置中心不一致
2. 如果远端没有为线程池配置单独告警的话，调用对应的getNotify()方法就会抛出异常。您是想反馈不配置告警，不应该抛异常么

**Comment by Gahon1995** [comment]
1. 我理解的是第一次加载应该会优先从配置文件加载吧，然后配置中心通过`AbstractCoreThreadPoolDynamicRefresh`更新配置，我想的场景可能就是配置中心因为某些原因临时调整了线程池配置，但是重新更新服务时，没注意远端配置的话就可能导致以为使用的是服务配置文件里的配置。当然这种应该也不属于比较重要的情况，我只是提一句
2. 我以为使用配置中心进行配置的时候，如果没有单独为线程池配置告警策略时，会使用默认的告警配置呢

**Comment by acmenlt** [comment]
@Gahon1995 第一个问题，可以先 Debug 下源码，了解下交互流程；第二个问题，hippo4j 支持公共告警策略，同时也支持线程池个性化报警配置，具体参考配置文件说明 https://hippox.cn/pages/2f674h/
