### ISSUE TITLE
队列长度不能动态修改

### ISSUE THREAD

**Issue by luocunhao** [acmenlt/dynamic-threadpool#168]

**Comment by acmenlt** [comment]
@luocunhao 请提供更详细的说明

**Comment by luocunhao** [comment]
1.yaml配置可变阻塞队列类型
`blocking-queue: 'ResizableCapacityLinkedBlockIngQueue'  # 阻塞队列名称，参考 QueueTypeEnum，支持 SPI`
2.修改queue-capacity
`private boolean checkConsistency(String threadPoolId, ExecutorProperties properties) {
        ExecutorProperties beforeProperties = GlobalCoreThreadPoolManage.getProperties(properties.getThreadPoolId());
        ThreadPoolExecutor executor = GlobalThreadPoolManage.getExecutorService(threadPoolId).getExecutor();

        boolean result = !Objects.equals(beforeProperties.getCorePoolSize(), properties.getCorePoolSize())
                || !Objects.equals(beforeProperties.getMaximumPoolSize(), properties.getMaximumPoolSize())
                || !Objects.equals(beforeProperties.getAllowCoreThreadTimeOut(), properties.getAllowCoreThreadTimeOut())
                || !Objects.equals(beforeProperties.getExecuteTimeOut(), properties.getExecuteTimeOut())
                || !Objects.equals(beforeProperties.getKeepAliveTime(), properties.getKeepAliveTime())
                || !Objects.equals(beforeProperties.getRejectedHandler(), properties.getRejectedHandler())
                ||
                (
                        !Objects.equals(beforeProperties.getQueueCapacity(), properties.getQueueCapacity())
                                && **Objects.equals(QueueTypeEnum.RESIZABLE_LINKED_BLOCKING_QUEUE.name, executor.getQueue().getClass().getSimpleName())**
                );

        return result;
    }`
最后一个!!判断为fasle导致不能动态修改容量

**Comment by luocunhao** [comment]
//这是workQueen
String threadPoolId = "custom-dynamic";
        ThreadPoolExecutor dynamicExecutor = ThreadPoolBuilder.builder()
                .threadFactory(threadPoolId)
                .threadPoolId(threadPoolId)
                .corePoolSize(8)
                .maxPoolNum(16)
                .workQueue(new ResizableCapacityLinkedBlockIngQueue(1024))
                .rejected(new ThreadPoolExecutor.AbortPolicy())
                .keepAliveTime(6000, TimeUnit.MILLISECONDS)
                .dynamicPool()
                .build();
        return dynamicExecutor;

**Comment by acmenlt** [comment]
我修改后是可以动态获取的

2022-04-01 18:24:20.193  INFO 42791 --- [namic.refresh-0] s.r.AbstractCoreThreadPoolDynamicRefresh : [MESSAGE-PRODUCE] Changed thread pool. 
    coreSize :: [1 => 1]
    maxSize :: [2 => 2]
    queueType :: [ResizableCapacityLinkedBlockIngQueue => ResizableCapacityLinkedBlockIngQueue]
    **capacity :: [2 => 200]**
    keepAliveTime :: [6691 => 6691]
    executeTimeOut :: [900 => 900]
    rejectedType :: [DiscardOldestPolicy => DiscardOldestPolicy]
    allowCoreThreadTimeOut :: [false => false]

**Comment by luocunhao** [comment]
<dependency>
            <groupId>cn.hippo4j</groupId>
            <artifactId>hippo4j-core-spring-boot-starter</artifactId>
            <version>1.2.0-RC1</version>
        </dependency>
你的版本是哪个，我上面的配置哪个地方有问题吗

**Comment by acmenlt** [comment]
> cn.hippo4j hippo4j-core-spring-boot-starter 1.2.0-RC1 你的版本是哪个，我上面的配置哪个地方有问题吗

版本相同，请提供详细的配置，以及操作步骤

**Comment by luocunhao** [comment]
coreSize和maxSize都能动态修改
1.yaml
`spring:
  dynamic:
    thread-pool:
      enable: true  # 是否开启动态线程池
      banner: true  # 是否打印 banner
      collect: false  # 是否开启线程池数据采集，对接 Prometheus
      notify-platforms:  # 通知报警平台
        - platform: 'DING'  # 钉钉
          secret-key: xxx
      nacos:  # nacos apollo 任选其一
        data-id: xxx.yml
        group: DEFAULT_GROUP
      config-file-type: yml  # 配置中心文件格式
      # 全局通知配置
      alarm: true  # 是否报警
      check-state-interval: 3000  # 检查线程池状态，是否达到报警条件，单位毫秒
      active-alarm: 80  # 活跃度报警阈值；假设线程池最大线程数 10，当线程数达到 8 发起报警
      capacity-alarm: 80  # 容量报警阈值；假设阻塞队列容量 100，当容量达到 80 发起报警
      alarm-interval: 8  # 报警间隔，同一线程池下同一报警纬度，在 interval 时间内只会报警一次，单位秒
      receive: xxxx# 企业微信填写用户 ID（填写其它将无法达到 @ 效果）、钉钉填手机号、飞书填 ou_ 开头唯一 ID
      # 线程池配置
      executors:
        - thread-pool-id: 'custom-dynamic'  # 线程池标识
          core-pool-size: 4  # 核心线程数
          maximum-pool-size: 16  # 最大线程数
          queue-capacity: 1024  # 阻塞队列大小
          execute-time-out: 1000  # 执行超时时间，超过此时间发起报警
          blocking-queue: 'ResizableCapacityLinkedBlockIngQueue'  # 阻塞队列名称，参考 QueueTypeEnum，支持 SPI
          rejected-handler: 'AbortPolicy'  # 拒绝策略名称，参考 RejectedPolicies，支持 SPI
          keep-alive-time: 1024  # 线程存活时间，单位秒  
          allow-core-thread-time-out: true  # 是否允许核心线程超时
          thread-name-prefix: 'custom-dynamic'  # 线程名称前缀
          notify:  # 通知配置，线程池中通知配置如果存在，则会覆盖全局通知配置
            is-alarm: true  # 是否报警
            active-alarm: 80  # 活跃度报警阈值；假设线程池最大线程数 10，当线程数达到 8 发起报警
            capacity-alarm: 80  # 容量报警阈值；假设阻塞队列容量 100，当容量达到 80 发起报警
            interval: 8  # 报警间隔，同一线程池下同一报警纬度，在 interval 时间内只会报警一次，单位分钟
            receive: xxx# 企业微信填写用户 ID（填写其它将无法达到 @ 效果）、钉钉填手机号、飞书填 ou_ 开头唯一 ID`
2.ThreadPoolConfig
`@Configuration
public class ThreadPoolConfig {

    @Bean
    @DynamicThreadPool
    public ThreadPoolExecutor dynamicThreadPoolExecutor() {
        String threadPoolId = "custom-dynamic";
        ThreadPoolExecutor dynamicExecutor = ThreadPoolBuilder.builder()
                .threadFactory(threadPoolId)
                .threadPoolId(threadPoolId)
                .corePoolSize(8)
                .maxPoolNum(16)
                .workQueue(new ResizableCapacityLinkedBlockIngQueue(1024))
                .rejected(new ThreadPoolExecutor.AbortPolicy())
                .keepAliveTime(6000, TimeUnit.MILLISECONDS)
                .dynamicPool()
                .build();
        return dynamicExecutor;
    }
}
`

**Comment by acmenlt** [comment]
@luocunhao 麻烦调整下样式，这样很难发现细节问题

**Comment by luocunhao** [comment]
已经解决了，好像是代码有缓存
