### ISSUE TITLE
线程池参数能否支持服务节点级别的配置

### ISSUE THREAD

**Issue by yongjie1992** [acmenlt/dynamic-threadpool#18]
作者你好，我试用了一下工程发现微服务下多个节点的配置不能差异化，只要一个节点的配置修改，其他节点的配置也会相应改变，后期有规划把配置细化到服务下的不同实例吗

**Comment by acmenlt** [comment]
> 作者你好，我试用了一下工程发现微服务下多个节点的配置不能差异化，只要一个节点的配置修改，其他节点的配置也会相应改变，配置有规划把配置细化到服务下的不同实例吗

支持客户端集群部署内差异化配置，您可以看下控制台的线程池实例列表

http://localhost:6691/index.html#/hippo4j/threadPool/instanceList

**Comment by yongjie1992** [comment]
试了一下，有个问题是这样的：
客户端起了两个实例A1和A2，A1修改线程池配置后A2重启会不停的打印下面的信息：
  2021-12-03 15:01:34.433  INFO 84569 --- [olling.executor] cn.hippo4j.starter.core.ClientWorker     : [Polling resp] config 
  changed. dataId=my-dtp, group=dtp-client, tenant=b2b
我跟踪了下代码发现，在client端长轮询线程里会不停请求服务端获取更新的配置并刷新缓存，而server端比较md5的时候因为比较的是缓存里的配置（ConfigCacheService#CACHE,还是原来的配置）总是不相同，所以又会告知client端配置有变化，client端又会去实时拉去最新配置，循环往复！

**Comment by acmenlt** [comment]
非常感谢您提供的这个信息，这个问题我想可能是存在的，需要验证下

**Comment by acmenlt** [comment]
> 试了一下，有个问题是这样的： 客户端起了两个实例A1和A2，A1修改线程池配置后A2重启会不停的打印下面的信息： 2021-12-03 15:01:34.433 INFO 84569 --- [olling.executor] cn.hippo4j.starter.core.ClientWorker : [Polling resp] config changed. dataId=my-dtp, group=dtp-client, tenant=b2b 我跟踪了下代码发现，在client端长轮询线程里会不停请求服务端获取更新的配置并刷新缓存，而server端比较md5的时候因为比较的是缓存里的配置（ConfigCacheService#CACHE,还是原来的配置）总是不相同，所以又会告知client端配置有变化，client端又会去实时拉去最新配置，循环往复！

非常感谢您提供的这个信息，这个问题我想可能是存在的，需要验证下

**Comment by yongjie1992** [comment]
> > 试一下，有问题是这样的： 客户端开始两个实例A1和A2，A1修改线程池配置后A2重启会不停的打印下面的信息： 2021-12-03 15:01:34.433 INFO 84569 -- - [olling.executor] cn.hippo4j.starter.core.ClientWorker ：[轮询响应] 配置已 更改。dataId=my-dtp, group=dtp-client,tenant=b2b 我查了下代码发现，在客户端长轮询线程会请求服务端获取更新的配置并刷新，而服务器端比较md5的因为比较是在挑选里的配置（ConfigCacheService#CACHE，还是原来的配置）总是不一样，所以又会通知客户端有变化，客户端去实时配置最新配置，循环往复！
> 
> 我试了下，并没有复现这个问题。说下我的步骤
> 
> 1. 启动服务端，启动两个客户端 A1、A2
> 2. 在服务端 [线程池实例页面] 修改 A1 实例线程池的参数
> 3. 此时重启 A2 应用，A2 并没有出现不停打印 config changed
> 
> 您可以尝试拉取下 develop 最新代码，或者提供下更详细的问题复现步骤。

步骤没错，唯一的区别是我在单独的项目下部署的客户端代码，使用项目的example子项目也无法复现

**Comment by acmenlt** [comment]
> > > 试一下，有问题是这样的： 客户端开始两个实例A1和A2，A1修改线程池配置后A2重启会不停的打印下面的信息： 2021-12-03 15:01:34.433 INFO 84569 -- - [olling.executor] cn.hippo4j.starter.core.ClientWorker ：[轮询响应] 配置已 更改。dataId=my-dtp, group=dtp-client,tenant=b2b 我查了下代码发现，在客户端长轮询线程会请求服务端获取更新的配置并刷新，而服务器端比较md5的因为比较是在挑选里的配置（ConfigCacheService#CACHE，还是原来的配置）总是不一样，所以又会通知客户端有变化，客户端去实时配置最新配置，循环往复！
> > 
> > 
> > 我试了下，并没有复现这个问题。说下我的步骤
> > 
> > 1. 启动服务端，启动两个客户端 A1、A2
> > 2. 在服务端 [线程池实例页面] 修改 A1 实例线程池的参数
> > 3. 此时重启 A2 应用，A2 并没有出现不停打印 config changed
> > 
> > 您可以尝试拉取下 develop 最新代码，或者提供下更详细的问题复现步骤。
> 
> 步骤没错，唯一的区别是我在单独的项目下部署的客户端代码，使用项目的example子项目也无法复现

有没有可能引入的 hippo-starter 版本有问题，之前是出现过这种问题，不过后来我修复了

**Comment by yongjie1992** [comment]
> > > > 试一下，有问题是这样的： 客户端开始两个实例A1和A2，A1修改线程池配置后A2重启会不停的打印下面的信息： 2021-12-03 15:01:34.433 INFO 84569 -- - [olling.executor] cn.hippo4j.starter.core.ClientWorker ：[轮询响应] 配置已 更改。dataId=my-dtp, group=dtp-client,tenant=b2b 我查了下代码发现，在客户端长轮询线程会请求服务端获取更新的配置并刷新，而服务器端比较md5的因为比较是在挑选里的配置（ConfigCacheService#CACHE，还是原来的配置）总是不一样，所以又会通知客户端有变化，客户端去实时配置最新配置，循环往复！
> > > 
> > > 
> > > 我试了下，并没有复现这个问题。说下我的步骤
> > > 
> > > 1. 启动服务端，启动两个客户端 A1、A2
> > > 2. 在服务端 [线程池实例页面] 修改 A1 实例线程池的参数
> > > 3. 此时重启 A2 应用，A2 并没有出现不停打印 config changed
> > > 
> > > 您可以尝试拉取下 develop 最新代码，或者提供下更详细的问题复现步骤。
> > 
> > 
> > 步骤没错，唯一的区别是我在单独的项目下部署的客户端代码，使用项目的example子项目也无法复现
> 
> 有没有可能引入的 hippo-starter 版本有问题，之前是出现过这种问题，不过后来我修复了

版本是1.0.0-RC3

**Comment by acmenlt** [comment]
> > > > > 试一下，有问题是这样的： 客户端开始两个实例A1和A2，A1修改线程池配置后A2重启会不停的打印下面的信息： 2021-12-03 15:01:34.433 INFO 84569 -- - [olling.executor] cn.hippo4j.starter.core.ClientWorker ：[轮询响应] 配置已 更改。dataId=my-dtp, group=dtp-client,tenant=b2b 我查了下代码发现，在客户端长轮询线程会请求服务端获取更新的配置并刷新，而服务器端比较md5的因为比较是在挑选里的配置（ConfigCacheService#CACHE，还是原来的配置）总是不一样，所以又会通知客户端有变化，客户端去实时配置最新配置，循环往复！
> > > > 
> > > > 
> > > > 我试了下，并没有复现这个问题。说下我的步骤
> > > > 
> > > > 1. 启动服务端，启动两个客户端 A1、A2
> > > > 2. 在服务端 [线程池实例页面] 修改 A1 实例线程池的参数
> > > > 3. 此时重启 A2 应用，A2 并没有出现不停打印 config changed
> > > > 
> > > > 您可以尝试拉取下 develop 最新代码，或者提供下更详细的问题复现步骤。
> > > 
> > > 
> > > 步骤没错，唯一的区别是我在单独的项目下部署的客户端代码，使用项目的example子项目也无法复现
> > 
> > 
> > 有没有可能引入的 hippo-starter 版本有问题，之前是出现过这种问题，不过后来我修复了
> 
> 版本是1.0.0-RC3

请使用最新的 0.9.0。RC3 版本是之前的测试版本，确实存在上述问题
