### ISSUE TITLE
关于 DTP（动态线程池）相关文章

### ISSUE THREAD

**Issue by acmenlt** [acmenlt/dynamic-threadpool#2]
大佬们好，

此 Issue 会展示动态线程池（Dynamic-ThreadPool）相关的使用介绍、上线生产文章，并且后续会逐步完善动态线程池项目的相关建设，敬请期待 :blush:。

**如果您有好的意见，也欢迎评论反馈！**

**Comment by GGGGGHT** [comment]
大佬 关于动态线程池 我有个简单的想法 是否可以通过JMX监控 线程池的状态 从而到达实现动态线程池的效果

**Comment by GGGGGHT** [comment]
不过`Executor`似乎不是JMX所支持的类型

**Comment by acmenlt** [comment]
> 大佬 关于动态线程池 我有个简单的想法 是否可以通过JMX监控 线程池的状态 从而到达实现动态线程池的效果

您好，关于线程池监控，移步 Issue[（#3）](https://github.com/acmenlt/dynamic-threadpool/issues/3)，已回复
