### ISSUE TITLE
优化客户端多实例集群部署，针对单实例线程池差异化配置

### ISSUE THREAD

**Issue by acmenlt** [acmenlt/dynamic-threadpool#22]
当客户端集群部署多个实例时，针对单实例修改线程池配置，不会影响其它实例配置

**Comment by acmenlt** [comment]
已完成，待合并

**Comment by gaochengyidlmu** [comment]
Hello，为什么会有这种需求，现在都是 K8S 部署，每个节点的性能差异应该是被抹平了的。
如果单实例修改了，下次重启的时候，是否仍然使用修改后的实例配置。有可能重启的时候，分配的 ip 都不同，那不是没法找到配置了吗。

**Comment by acmenlt** [comment]
您好，我理解这是两个问题

1. K8s 部署，单实例性能差异抹平

这句话本身是对的。但是对于线程池来说，运行任务不会均匀分配到集群中的每一台机器，所以需要差异化配置

2. 如果单实例修改了，下次重启的时候，是否仍然使用修改后的实例配置。有可能重启的时候，分配的 ip 都不同，那不是没法找到配置了吗

单实例修改，重启时如果 IP +唯一标识 不变，延续单实例修改后的配置；IP 变了，则使用公共的

**Comment by gaochengyidlmu** [comment]
@acmenlt 感谢回答。
运行任务不会均匀分配，这种能不能提供相关场景。
我能想到的就是根据 id 分片的时候，id hash 不均导致的任务倾斜。但是这种应该是要避免的情况，因为会引起整个链路的任务不均。这种差异化配置，应该是一种临时解决方案吧。

**Comment by acmenlt** [comment]
@gaochengyidlmu 举个最简单的例子

集群环境下，线程池内远程调用服务或者操作数据库，因为网络抖动或部分数据查询缓慢导致的线程池任务执行慢，线程池处理速度就会下降，任务就会堆积

如果为了保证任务不被丢弃，可以临时修改阻塞队列的大小。而这种操作是不能被广播到集群的

线程池的场景太多了，没必要纠结差异化配置，可以理解成是一种增强功能

**Comment by gaochengyidlmu** [comment]
@acmenlt 所以这个临时修改应该是服务端检测后，自动修改的，对吧。

**Comment by acmenlt** [comment]
@gaochengyidlmu 这个问题又是另外一个纬度，自动扩容。1.0 不会支持

正确的步骤应该是：
1. 设置线程池报警以及对应的报警参数
2. 线程池运行过载后，发出报警通知
3. 人工操作某一节点的数据，进行修改

**Comment by gaochengyidlmu** [comment]
@acmenlt 好的，感谢！
这个功能我认为是结合自动扩容后会有效果，否则人工干预，可能还没来得及处理就已经积压处理完成了。
但是自动扩容又会引发很多其他的问题，甚至可能导致 OOM，那个应该更有挑战性了。
