### ISSUE TITLE
DTP（动态线程池）项目如何实现线程池监控

### ISSUE THREAD

**Issue by acmenlt** [acmenlt/dynamic-threadpool#3]
![image](https://user-images.githubusercontent.com/77398366/129436200-73e42c87-3ba8-428e-91a4-b626f83b9bfe.png)

**Comment by acmenlt** [comment]
关于 DTP 项目中对线程池监控，小编初步想法是提供两种方式，实时查看以及定时上报
- Server 端实时查看服务下各节点 Client 端线程池的运行指标
- Client 端汇总运行时指标数据，定时上报 Server 端，进行不同维度的展示

![image](https://user-images.githubusercontent.com/77398366/129437342-8c6fdac7-578c-4611-8733-808e2a2e4d8e.png)

通过上述的两种方式，可以将监控控制在 Server 端，根据需求集中查看

我理解您说的JMX 监控是对 Client 端进行直接监控，如果一个应用部署了十几个节点，监控起来不太方便

**Comment by GGGGGHT** [comment]
通过Spring获取到该服务中的所有线程池对象,通过JMX监控,并且注册线程向Server上报

**Comment by acmenlt** [comment]
> 通过Spring获取到该服务中的所有线程池对象,通过JMX监控,并且注册线程向Server上报

上报这一块咱们思路上是一致的，不过是否需要 JMX 技术监控线程池，我需要调研下。非常感谢提出的建议！
