### ISSUE TITLE
什么时候发布 1.0.0 RELEASE 

### ISSUE THREAD

**Issue by haoxd** [acmenlt/dynamic-threadpool#4]

**Comment by acmenlt** [comment]
目前还在规划阶段，所以 1.0.0.RELEASE TODO

最早时希望动态线程池不依赖任何中间件。但是，后来考虑这个想法有些欠缺

所以，后来决定，保留原有配置中心、注册中心的设计，并引入主流 Nacos、Apollo 等框架，类似 Seata 设计，可自主选择

**Comment by haoxd** [comment]
作者你好，首先对你的开源精神表示感谢，我今天部署看了下代码，目前已经支持
动态修改、监控、报警等特性了吧

**Comment by acmenlt** [comment]
> 作者你好，首先对你的开源精神表示感谢，我今天开发研究下代码，目前已经支持
> 动态修改、监控、报警等特性

感谢！

DTP 项目关于动态修改、报警、监控已支持，但是后续会继续优化，目前还不是终态
