### ISSUE TITLE
DiscoveryClient bean 冲突

### ISSUE THREAD

**Issue by dong4j** [acmenlt/dynamic-threadpool#44]
如果在 springcloud 环境下，因为存在 org.springframework.cloud.client.discovery.DiscoveryClient 导致在装配 cn.hippo4j.starter.core.DiscoveryClient 时出现冲突，需要修改为或设置 Bean.value 属性

```java
@Bean
public DiscoveryClient customDiscoveryClient(HttpAgent httpAgent, InstanceInfo instanceInfo) {
    return new DiscoveryClient(httpAgent, instanceInfo);
}
```

**Comment by acmenlt** [comment]
收到，您有兴趣提交个 pr 么，设置 bean 名称为 hippo4jDiscoveryClient

**Comment by dong4j** [comment]
不好意思 才看到 下次有问题我就直接提 pr 了 😄
