### ISSUE TITLE
client 如何获取到 server 事件通知

### ISSUE THREAD

**Issue by jia2118290** [acmenlt/dynamic-threadpool#56]
请教一下    server 端 ConfigChangePublisher.notifyConfigChange(new LocalDataChangeEvent(identify, ContentUtil.getGroupKey(configInfo)));  发布了事件，client 怎么获取到事件。
这是2个系统，如果实现交互
client 的  cn.hippo4j.starter.core.ThreadPoolDynamicRefresh#refreshDynamicPool(java.lang.String)  调用的上层是哪里？

**Comment by jia2118290** [comment]
server 通知  client 后，client 的  cn.hippo4j.starter.core.ThreadPoolDynamicRefresh#refreshDynamicPool(java.lang.String)  
调用的上层是哪里？

**Comment by acmenlt** [comment]
了解一下长轮询机制

Client 会发起一个请求，被 Server 端挂起，如果 Server 端配置有变更，会将请求返回

如果查看源码，关注下面两个类

Server 端 `cn.hippo4j.config.service.LongPollingService#generateResponse`

Client 端 `cn.hippo4j.starter.core.ClientWorker.LongPollingRunnable`

**Comment by jia2118290** [comment]
如果client 节点过多，长轮询  server 会比较有压力，server端宕机会影响所有client 端。是否考虑server端集群部署

**Comment by acmenlt** [comment]
Server 端机群部署在规划中
