### ISSUE TITLE
HttpGet 响应 code 异常. [code] 403 [url] http://localhost:6691/hippo4j/v1/cs/health/check

### ISSUE THREAD

**Issue by Memorydoc** [acmenlt/dynamic-threadpool#59]
按照文档来的 启动连接 server端发现心跳会抱异常 HttpScheduledHealthCheck

**Comment by acmenlt** [comment]
Server 端默认需要鉴权，如果说启动 Client 端与之交互，请确认 Client 端是否配置用户名、密码

**Comment by acmenlt** [comment]
已解决，starter 包与 server 包版本不一致导致
