### ISSUE TITLE
关于线程池监控的疑惑

### ISSUE THREAD

**Issue by Professor-mai** [acmenlt/dynamic-threadpool#62]
1. 这里使用延时队列去上报数据，是否会对系统造成性能上的损耗

**Comment by acmenlt** [comment]
对系统加的任何一种操作，都会是一种性能损耗；需要看系统是否可以容忍这个损耗，如果认为线程池监控会影响系统运行，Starter 提供了开关，可以关闭此操作

**Comment by Professor-mai** [comment]
一小时一个线程池大约是720条数据，假设我现在是100台机器，每台机器10个线程池，一小时的数据量就是72w条数据，这个数据量是不是有点大了

**Comment by Professor-mai** [comment]
请问一下，有考虑集群环境下要怎么采集线程池运行数据怎么实现吗

**Comment by acmenlt** [comment]
> 一小时一个线程池大约是720条数据，假设我现在是100台机器，每台机器10个线程池，一小时的数据量就是72w条数据，这个数据量是不是有点大了

我们可以算一下，假设有 100 个应用，每个应用部署 10 个节点

假设数据有效期为 1 小时，那么可以产出的数据是 72 万，一天也就是 1728 万

对于 MySQL 而言，几千万数据量以下针对索引的查询，都不会产生性能瓶颈

**Comment by acmenlt** [comment]
> 请问一下，有考虑集群环境下要怎么采集线程池运行数据怎么实现吗

集群下的采集和单节点采集是一致的，通过唯一标识确认应用

**Comment by acmenlt** [comment]
> > 一小时一个线程池大约是720条数据，假设我现在是100台机器，每台机器10个线程池，一小时的数据量就是72w条数据，这个数据量是不是有点大了
> 
> 我们可以算一下，假设有 100 个应用，每个应用部署 10 个节点
> 
> 假设数据有效期为 1 小时，那么可以产出的数据是 72 万，一天也就是 1728 万
> 
> 对于 MySQL 而言，几千万数据量以下针对索引的查询，都不会产生性能瓶颈

服务端有一个定时线程池，删除数据有效期之外的数据。比如你设置数据有效期一小时，那么每分钟执行一次删除一小时以外的数据
