### ISSUE TITLE
Hippo 修改线程池配置时报错：config_info 表找不到

### ISSUE THREAD

**Issue by acmenlt** [acmenlt/dynamic-threadpool#7]
## 问题原因

对项目的基础表名进行了修改，如下：

- config_info -> config
- item_info -> item
- tenant_info -> tenant

## 解决方案

执行 [初始化 SQL 脚本](https://github.com/acmenlt/dynamic-threadpool/blob/develop/server/src/main/resources/hippo_manager.sql) 重新导入

**Comment by liuboflyon145** [comment]
sql 脚本在哪获取

**Comment by acmenlt** [comment]
> sql 脚本在哪获取

https://github.com/acmenlt/dynamic-threadpool/issues/7#issuecomment-1055131996

**Comment by acmenlt** [comment]
> sql 脚本在哪获取

https://github.com/acmenlt/dynamic-threadpool/tree/develop/hippo4j-server/conf
