### ISSUE TITLE
动态更新CorePoolSize变小，会优雅下线吗？

### ISSUE THREAD

**Issue by Professor-mai** [acmenlt/dynamic-threadpool#71]

**Comment by acmenlt** [comment]
先说结论，会优雅下线。设置流程如下：

![image](https://user-images.githubusercontent.com/77398366/148783384-d658d457-64ce-4508-978a-378576a7f209.png)

![image](https://user-images.githubusercontent.com/77398366/148783403-797c22ac-e212-48eb-a437-6ca1b3eb9482.png)

1. 判断设置的 new corePoolSize 必须大于 0，否则抛出异常
2. 直接替换线程池的 corePoolSize 为 new corePoolSize
3. 判断线程池的工作线程是否大于 new corePoolSize，条件如果成立则执行中断多余空闲的线程
4. 如果上述条件不成立，判断 corePoolSize 是否小于 new corePoolSize，如果小于说明需要创建新的核心线程

关于第四步，有一个小知识点，线程池作者为了保证线程资源不浪费而做出的优化

执行第四步时通过注释得知，并不知道需要创建多少线程，而为了保证线程资源不会被浪费，这里会依据 workQueue#size 和 delata 来计算出需要创建的线程数量 k

Math#min 会返回两个值中小的那个，小编想到了三种情况，我们这里来假设下

1. 假设 workQueue#size == 0，那么 k 也等于零，证明并没有阻塞住的任务需要执行，k-- > 0 表达式并不成立，就不会执行 #addWorker
2. 假设 workQueue#size > 0 && < delta，此时任务队列里有待执行任务。k-- > 0 表达式成立，一般情况会创建 workQueue#size 个新核心线程，二般情况下是线程池里其它线程把 workQueue 的任务清了，就会跳出创建流程
3. 假设 workQueue#size > 0 && > delta，这种情况最多会创建 delata 个新核心线程

**Comment by Professor-mai** [comment]
关于第三点，条件如果成立则执行中断多余空闲的线程，如果线程一直不空闲咋办

**Comment by acmenlt** [comment]
线程如果在运行，不会强行中断，除非 shutdownNow

**Comment by Professor-mai** [comment]
那线程一直在运行，又不断有任务进来，那会怎么样，好像是会阻塞任务？等待该线程的任务运行完成后再下线？

**Comment by acmenlt** [comment]
请参考线程池的运行机制
