### ISSUE TITLE
[BUG] startup.cmd 脚本启动错误

### ISSUE THREAD

**Issue by acmenlt** [acmenlt/dynamic-threadpool#79]

**Comment by baymax55** [comment]
我试了下，cmd脚本没有问题。
目前我发现的问题有：
1.该项目目前只适应jdk1.8。jdk11或者17打包会有问题
2.在主pom打包时会报错，注释gpg插件后可以正常打包
3.执行cmd之前，请先确认jar正常生成且已修改数据库配置文件和数据初始化完成

如下是我启动成功页面：
环境：win11+jdk1.8+maven3.6.3
![image](https://user-images.githubusercontent.com/35788491/152666032-60afcc1c-0bab-4a78-9b30-710d2a48fcbd.png)

**Comment by acmenlt** [comment]
这个问题的背景是使用 hippo4j 的一位小伙伴提出的。

我猜测 cmd 脚本可能无法正确读取 application.properties 配置，您可以帮忙测试下，如果没有问题请帮忙关闭 issue，谢谢。
