### ISSUE TITLE
疑问：Lease#isExpired方法的计算方式

### ISSUE THREAD

**Issue by zhaoguogeng** [acmenlt/dynamic-threadpool#81]
![image](https://user-images.githubusercontent.com/59593786/150087432-2d5ecb80-882b-467d-9b94-050c99677126.png)
Lease#renew方法会更新最后一次心跳时间，但是额外加了一个duration，感觉破坏了lastUpdateTimestamp的语义；
在isExpired(Long)里，又加了一次duration，并且加了一个additionalLeaseMs。看了一下这个方法的调用，是在定时任务EvictionTask调用的，这里想不通，lease是否过期的判断，为什么会跟定时任务是否延迟执行有关？就算两次EvictionTask任务间隔1小时，lease的过期也只需要判断System.currentTimeMillis() > lastUpdateTimestamp + duration就可以了吧？

**Comment by zhaoguogeng** [comment]
我去看了一下eureka的源码，源码里注释说加了两遍duration是一个bug，但是鉴于影响范围比较广，就不修复了。
不过咱们是一个新的项目，就不要引入这种bug了吧。

**Comment by acmenlt** [comment]
是否可以认为，添加两次 duration 是一种不合理行为，但是不影响业务功能
