### ISSUE TITLE
控制消息推送报警频率的方法有并发安全的问题

### ISSUE THREAD

**Issue by zhaoguogeng** [acmenlt/dynamic-threadpool#82]
检查是否发送报警的方法是放到线程池中并发执行的，但AlarmControlHandler#isSendAlarm却不是并发安全的，并发的情况下会出现报警频率控制失效，发送重复报警的问题
![image](https://user-images.githubusercontent.com/59593786/150296143-edf015f4-920c-4a35-b39a-43837196d4c8.png)

**Comment by acmenlt** [comment]
收到，这个问题会在 1.0 发布时解决

**Comment by acmenlt** [comment]
为每一个线程池对应的报警通知平台配置把可重入锁，减少锁的碰撞同时，也能防止消息错误推送
