### ISSUE TITLE
Ip:Port no data

### ISSUE THREAD

**Issue by Redick01** [acmenlt/dynamic-threadpool#88]
``the Ip:Port data is null of threadpool manage page . why?

this is my config

**yml**

spring:
  profiles:
    active: dev
  # 应用配置
  application:
    name: dy-test

  # 动态线程池配置
  dynamic:
    thread-pool:
      server-addr: http://localhost:6691
      namespace: apollo
      item-id: dy-test
      username: admin
      password: 123456
      enable: true

**threadpool java config**

` 
@Bean
@DynamicThreadPool
   public ThreadPoolExecutor dynamicThreadPoolExecutor() {
        return ThreadPoolBuilder.builder()
                .threadFactory("apollo-thread-pool")
                .dynamicPool()
                /**
                 * 测试线程任务装饰器.
                 * 如果需要查看详情, 跳转 {@link TaskDecoratorTest}
                 */
                .waitForTasksToCompleteOnShutdown(true)
                .awaitTerminationMillis(5000)
                .build();
    }
`

**Comment by acmenlt** [comment]
可以参考 spring boot 集成文档，https://hippox.cn/pages/2f674a/

**Comment by Redick01** [comment]
It has been solved
