### ISSUE TITLE
BaseInstanceRegistry读写锁的使用

### ISSUE THREAD

**Issue by zhaoguogeng** [acmenlt/dynamic-threadpool#91]
这个类的代码应该是参考了eureka的AbstractInstanceRegistry，eureka里使用读写锁，并且用了写操作(register、cancel……)加读锁，读操作(getApplicationDeltasFromMultipleRegions、getApplicationDeltas……)加写锁的骚操作，是为了实现客户端增量同步的功能。

但是本项目不涉及这块的功能，而且用作缓存的map都是线程安全的，是否可以去掉读写锁？并且本项目的BaseInstanceRegistry中register使用了读锁，remove使用了写锁，这块是基于什么考虑的？

**Comment by acmenlt** [comment]
感谢提出的问题。最初写 hippo4j 时为了尽快出功能模型，对细节把握的不太好，您提的这些问题会在 1.0 发布前改正
