### ISSUE TITLE
通过配置提供线程数自动伸缩功能

### ISSUE THREAD

**Issue by wxiaole** [acmenlt/dynamic-threadpool#93]
在线程达到警告状态时，如果开启了某个配置，可以自动 修改线程池的数据

**Comment by acmenlt** [comment]
这种方式不是很好控制资源的利用。比如说，当前虚拟机或 Pod 负载已经很高了，如果再进行扩容线程池的线程数，无疑会雪上加霜

这个 IDEA 很好，只是还没有考虑好如何引入

**Comment by wxiaole** [comment]
可以根据当前系统的负载来判断么。只要负载没有达到，那么就可以按照某个规则扩大。负载降下来，可以缩小么。只是在哪里去做这个判断还没考虑好。
