### ISSUE TITLE
发送报警的操作放到服务端会不会更合理

### ISSUE THREAD

**Issue by zhaoguogeng** [acmenlt/dynamic-threadpool#98]
客户端上报报警数据，服务端收集数据后，进行报警信息的实际发送，会不会更合理一些。

1、客户端没有外网环境。
实际场景中，各个微服务都是内网环境，通过网关对外提供服务。如果将发送报警的操作放在客户端，是不是意味着各个服务都要有外网环境，这个在生产中是做不到的。
2、提供spi的形式，每个客户端都要有报警的实现代码。
作为开源组件，提供spi的形式确实会更灵活。但公司应该都会有统一的办公软件，并不会频繁变动，将报警操作放在服务端实现，可以让代码更收敛一些，不会散落在各个客户端中。

**Comment by acmenlt** [comment]
这个提议很好，最近会完成这块功能重构

**Comment by acmenlt** [comment]
考虑后续会推出客户端线程池数据对接 Prometheus，采用这种模式，服务端就没必要再进行收集数据，则无法判断是否报警

所以，服务端与客户端都应有发送报警通知的能力，两者由客户端控制开其一即可
